# Generated by Django 3.2.13 on 2022-05-05 12:18

from django.db import migrations, models
import petstagr.main.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagr.main.common.validators.ValidatePhotoMaxSizeMB(5)]),
        ),
    ]
